include ../../scripts/adolc.flags

HEADERS=-I../../../inst/include

TAPOBJS=tapedoc.o

%.o: %.c
	@echo CC  $<
	@${CC} ${HEADERS} ${ADOLC_CFLAGS} -c $<
	
library: $(TAPOBJS)

clean:
	@if exist *.o del *.o
	@if exist error_out del error_out
	@if exist *~ del *~
